config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, skip: :registrations, controllers: { sessions: 'sessions' }

    resources :blogs
    resources :works
    resources :contacts

    root to: 'main#index'
  end
end

app/views/shared/_carousel.html.erb
<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="3000">
      <%= image_tag("slider.png", height: '400', width: '100%', class: "carousel-blur d-block w - 100", alt: 'slider') %>
      <div class="carousel-caption d-none d-md-block text-white">
        <h1 class="title">Автономные отопители</h1>
        <p class="body">Установка / Ремонт / Диагностика</p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="3000">
      <%= image_tag("slider.png", height: '400', width: '100%', class: "carousel-blur d-block w - 100", alt: 'slider') %>
      <div class="carousel-caption d-none d-md-block text-white">
        <h1 class="title">Тахографы</h1>
        <p class="body">Установка / Ремонт / Калибровка</p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="3000">
      <%= image_tag("slider.png", height: '400', width: '100%', class: "carousel-blur d-block w - 100", alt: 'slider') %>
      <div class="carousel-caption d-none d-md-block text-white">
        <h1 class="title">Автокондиционеры</h1>
        <p class="body">Диагностика / Ремонт / Заправка</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_errors.html.erb
<% if object&.errors&.full_messages&.any? %>
  <div class="alert alert-danger">
    <ul class=" text-start">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if notice || alert %>
  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>
<% else %>
  <% flash.each do |k, v| %>
  <%= tag.div v, class: "alert alert-#{k}", role: 'alert' %>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-top">
    <div class="container">
      <div class="row ">
        <div class="col-sm-6 col-md-5 col-lg-6 column-left">

          <b>Адрес: </b>
            <%= link_to '216км трассы М10, д. Миронежье, стоянка «Дубрава»','https://yandex.ru/maps/-/CCUC7OxGkA',
                                                           target: '_blank',
                                                            class: 'text-decoration-none text-reset' %>
          <br>
          <b>Часы работы: </b>9:00 - 20:00 ПН-СБ
          <br>
          <b>Телефон: </b>
            <%= phone_to '9201531212', '+7 (920) 153-12-12',
                                                            country_code: "7",
                                                            class: 'text-decoration-none text-reset' %>
          <br>
          <b>Email: </b>
            <%= mail_to 'kbsv69@mail.ru', 'kbsv69@mail.ru',
                                                            class: 'text-decoration-none text-reset' %>
        </div>

        <div class="col-sm-6 col-md-5 offset-md-2 col-lg-6 offset-lg-0 text-end column-right">

          <%= link_to 'Регистрационный номер свидетельства','https://rosavtotransport.ru/ru/activities/tachograph-control-eu/register-asc/?action=organization&district=69&id=864',
                                                          target: '_blank',
                                                           class: 'text-decoration-none text-reset' %>
          <b> RUS 975</b>
          <br>
          <%= link_to 'Реестр международных перевозок','https://rostransnadzor.gov.ru/deyatelnost/razresitelnye-dokumenty',
                                                          target: '_blank',
                                                           class: 'text-decoration-none text-reset' %>
          <b >
          <%= link_to 'МАП','https://share.red-soft.ru/index.php/s/nMt5o4Ht3TNFLDB/download?path=%2F&files=2023-02-16_Реестр_российских_перевозчиков.xls',
                                                           class: 'text-decoration-none text-reset' %>
          </b>

          <br>
          <%= link_to 'Министерство Транспорта | Тахографы ', 'https://mintrans.gov.ru/activities/214/98/documents',
                                                          target: '_blank',
                                                           class: 'text-decoration-none text-reset' %>

          <br>
          <%= link_to 'Оставить отзыв о нас Yandex.ru', 'https://yandex.ru/maps/org/avtonomki_takhografy_konditsionery/237157977971/reviews/?ll=35.211431%2C56.988715&z=16',
                                                          target: '_blank',
                                                           class: 'text-decoration-none text-reset' %>

        </div>
      </div>
    </div>


    <div class="arrow-up"
       <%= link_to image_tag("arrow-up-circle-fill.svg", size: '30'),'#', id: "scrollToTopBtn",class: 'arrow-image' %>
    </div>
  </div>


  <div class="footer-bottom">
    Copyright @2023 All rights reserved | This website made by NRN
  </div>
</footer>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-1 bg-white text-dark">
    <nav class="container-fluid">
      <input type="checkbox" id="dws-menu">
      <div class="label-menu">
        <label for="dws-menu"><%= image_tag 'list.svg', size: '30' %></label>
      </div>
      <nav class="d-flex nav-menu flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav nav-li col-12 col-lg-auto me-lg-auto mb-1 justify-content-center mb-md-0">
            <li class="image-menu">
              <%= nav_tab image_tag("house-fill.svg", size: '22', alt: t('menu.home')), root_path,
                          class: "nav-link", current_page: current_page %>
            </li>
            <li class="menu-start menu-home">
              <%= nav_tab t('menu.home'), root_path,
                          class: "nav-link", current_page: current_page %>
            </li>

            <li class="menu-start">
              <%= nav_tab t('menu.works'), works_path,
                          class: 'nav-link', current_page: current_page %>
            </li>
            <li class="menu-start">
              <%= nav_tab t('menu.blogs'), blogs_path,
                          class: 'nav-link', current_page: current_page %>
            </li>
            <li class="menu-start">
              <%= nav_tab t('menu.contacts'), contacts_path,
                          class: 'nav-link', current_page: current_page %>
            </li>
        </ul>

        <ul class="nav nav-language col-12 col-lg-auto mb-2 mb-md-0">
          <li class="dropdown">
            <%= link_to '#', class: 'nav-link px-2 dropdown-toggle text-dark',
                        data: {"bs-toggle": 'dropdown'} do %>
              <%= t I18n.locale %>
            <% end %>

            <ul class="dropdown-menu">
              <% I18n.available_locales.each do |locale| %>
                <li class="menu-lang">
                  <% if I18n.locale == locale %>
                    <%= tag.span t(locale), class: 'dropdown-item' %>
                  <% else %>
                    <%= link_to t(locale), url_for(locale: locale),
                                class: 'dropdown-item' %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>

        <ul class="nav nav-user col-12 col-lg-auto mb-1 mb-md-0 mb-1">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= link_to '#',
                          class: 'nav-link px-2 dropdown-toggle text-dark',
                          data: {"bs-toggle": 'dropdown'} do %>
                <% if current_user.admin? %>

                <%= image_tag("gear-fill.svg", size: '24') %>
                <% else %>
                  <%= current_user.email %>
                <% end %>
              <% end %>

              <ul class="dropdown-menu">
                <li>
                  <%= link_to t('menu.auth.sign_in.exit'), destroy_user_session_path,
                              class: 'dropdown-item',
                              data: {turbo_method: :delete} %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><button type="button" class="btn btn-default btn-circle btn-sm" data-bs-toggle="modal" data-bs-target="#sign_in">
              <%= image_tag("person-circle.svg", size: '22') %></li>

                <%= render 'shared/sign_in' %>

          <% end %>
        </ul>
      </nav>

      <div class="user-menu hidden">
      <nav class="d-flex user-menu flex-wrap align-items-center justify-content-center justify-content-lg-end">
        <ul class="nav user-language col-12 col-lg-auto mb-2 mb-md-0">
          <li class="dropdown">
            <%= link_to '#', class: 'nav-link px-2 dropdown-toggle text-dark',
                        data: {"bs-toggle": 'dropdown'} do %>
              <%= t I18n.locale %>
            <% end %>

            <ul class="dropdown-menu">
              <% I18n.available_locales.each do |locale| %>
                <li class="menu-lang">
                  <% if I18n.locale == locale %>
                    <%= tag.span t(locale), class: 'dropdown-item' %>
                  <% else %>
                    <%= link_to t(locale), url_for(locale: locale),
                                class: 'dropdown-item' %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>

        <ul class="nav user-user col-12 col-lg-auto mb-1 mb-md-0 mb-1">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= link_to '#',
                          class: 'nav-link px-2 dropdown-toggle text-dark',
                          data: {"bs-toggle": 'dropdown'} do %>
                <% if current_user.admin? %>

                  <%= image_tag("gear-fill.svg", size: '24') %>
                <% else %>
                  <%= current_user.email %>
                <% end %>
              <% end %>

              <ul class="dropdown-menu">
                <li>
                  <%= link_to t('menu.auth.sign_in.exit'), destroy_user_session_path,
                              class: 'dropdown-item',
                              data: {turbo_method: :delete} %>
                </li>
              </ul>
            </li>
          <% else %>

            <li>
              <%= link_to image_tag("person-circle.svg", size: '22'), new_user_session_path %>
            </li>

          <% end %>
        </ul>
        </nav>
      </div>
    </nav>
  </header>
<% end %>

app/views/shared/_sign_in.html.erb
<div class="modal hide fade" id="sign_in" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content text-dark">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <div id="flash">
            <%= render 'shared/flash' %>
          </div>
          <div class="row justify-content-center">
            <div class="col-md-6">
              <div class="title"><strong>
                <%= image_tag('person-profile.svg', class: 'image') %>
              </strong></div>

              <%= form_for(User.new,
                                        url: session_path(:user),
                                        html: { id: 'sign_in_user',
                                                data: { type: :json }},
                                        remote: true) do |f| %>

                <div class="form-group my-4">
                  <%= f.email_field    :email,
                                        autofocus: true,
                                        autocomplete: 'off',
                                        class: 'field',
                                        placeholder: 'Email' %>
                </div>

                <div class="form-group my-1">
                  <%= f.password_field  :password,
                                        autocomplete: 'off',
                                        class: 'field',
                                        placeholder: t('devise.autocomplete.password') %>
                </div>
                <div class="forgot">
                  <%= link_to t('devise.link.forgot_password'), new_user_password_path,
                                        class: 'forgot' %>
                </div>

                <div class="actions">
                  <%= f.submit t('devise.sessions.new.button'),
                                        class: 'btn btn-dark bt-sm' %>
                </div>

                <div class="sign_up">
                 only administration
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_uploaded_file.html.erb
<% unless object.file.url.nil? %>
  <div class="container">
    <div class="row">
      <hr>
      <div class="col-lg-6 col-md-6 mb-4">
        <div class="mb-1">

          <% filetype object.file.url %>
          <%=  link_to image_tag(@filetype, size: '24'), object.file.url, target: '_blank' %>
          <%= filename object.file.url  %>

          <br>
        </div>
      </div>
    </div>
  </div>
<%  end %>